# Generated by Django 2.0.6 on 2020-05-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='types',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
    ]
